# Dockerfile
FROM python:3.9

WORKDIR /app

COPY . .

CMD python concat_dados.py && python ope_mat.py && python repet_txt.py && python media.py && python palindromo.py && python par_ou_impar.py

#CMD ["python", "concat_dados.py"]
#CMD ["python", "ope_mat.py"]
#CMD ["python", "repet_txt.py"]
#CMD ["python", "media.py"]
#CMD ["python", "palindromo.py"]
#CMD ["python", "par_ou_impar.py"]